### ISSUE TITLE
数据集来源求证

### ISSUE THREAD

**Issue by Versocial** [evitamine4ever/Classical-Chinese-NER-RE-Dataset#1]
请问RE数据集来自于哪里，或者怎么引用

**Comment by beeevita** [comment]
您好，RE 数据集是我们自己标注的，以脚注形式引用即可。
\footnote{Classical-Chinese-NER-RE-Dataset \url{https://github.com/beeevita/Classical-Chinese-NER-RE-Dataset}}.

**Comment by Versocial** [comment]
谢谢

**Comment by Versocial** [comment]
另外，突然发现 [C-CLUE](https://github.com/jizijing/C-CLUE) 中的NER数据集似乎与这里的相同，请问是采用了他们的NER数据集吗，如果是，为什么没有采用他们的RE数据集而是重新标注？是因为RE集标注不良？RE的标注是在他们的基础上修正的吗？

**Comment by beeevita** [comment]
c-clue 的数据集就是我们这里标注的数据集，他们似乎没有对我们的工作标引用

**Comment by beeevita** [comment]
c-clue 的数据集就是我们这里标注的数据集，他们似乎没有对我们的工作标引用。参考 commit 时间即可

**Comment by Versocial** [comment]
好的，谢谢
